### PR TITLE
Possibility to specify HTTP Status Code has been added

### PR DESCRIPTION
**Pull request by vkamenski**
I've added possibility to specify http status code. According to specification http://json-rpc.org/wd/JSON-RPC-1-1-WD-20060807.html#ResponseStatusCodes status code may be changed to 500, 301 etc. Status code may be passed with "http_status_code" value passed into response info obj.

### CODE REVIEW

**Comment by tonyg** [comment]
Hi - I like the idea of this patch, but I'm having trouble seeing the patch history cleanly. Could I get you to (a) _rebase_ your master off tonyg/master, and then (b) open a fresh pull request? This one has a long and confusing history that is best dropped at this point, IMO.

**Comment by vkamenski** [comment]
Hi, 

I am newbie in git so could you please provide me instructions how to do this :)

**Comment by tonyg** [comment]
Well, I can point you at:
- http://git-scm.com/book/en/Git-Branching-Rebasing
- http://gitready.com/intermediate/2009/01/31/intro-to-rebase.html

which should help. But it might take a bit of experimenting, in particular
because your history has some patches that were applied differently in my
history.

... OK so I've just done a rebase, and dealt with the inevitable problems;
I'll push the rebased version of your change to my repository soon. I
suggest you delete your fork of erlang-rfc4627 and get a fresh fork from
mine to work on going forward. Thanks for the contribution, by the way!

Regards,
  Tony

On 15 May 2012 12:10, Valery Kamensky <
reply@reply.github.com

> wrote:
> 
> Hi,
> 
> I am newbie in git so could you please provide me instructions how to do
> this :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tonyg/erlang-rfc4627/pull/8#issuecomment-5719898

## 

Tony Garnock-Jones
tonygarnockjones@gmail.com
http://homepages.kcbbs.gen.nz/tonyg/

**Comment by vkamenski** [comment]
Thank you!

**Pull request closed without merging**
