### PR TITLE
Make rfc4627.erl more dialyzer friendly

### PR DESCRIPTION
**Pull request by matwey**
See commit message for details.

### CODE REVIEW

**Comment by tonyg** [comment]
Hi Matwey,

Thanks for the patch. There are two problems with it:
1. It doesn't compile: "src/rfc4627.erl:98: type byte() is a builtin type; it cannot be redefined"
2. It won't work on R12B.

I imagine fixing (1) should be straightforward; perhaps with (2) an ifdef could be used? See for example RabbitMQ's use of `-ifdef(use_specs)` and corresponding Makefile hackery.

**Comment by matwey** [comment]
Hm.. I will go rework it.
It is strange, but on R16B01, it is compiled.

**Comment by tonyg** [comment]
I still can't get it to compile as it stands on any of R13, R14, R15 or R16, but if I remove line 98 (definition of byte()) and update the `export_type` to match, it compiles for me. All that remains is making things work for R12B.

**Comment by matwey** [comment]
Ok, look at this.

**Comment by tonyg** [comment]
Looks great. Thanks!

**Pull request merged**
